baseURL = "https://strongaya.github.io/AYA-cancer-data-schema/"
theme = "hugo-book"
title = "STRONG AYA Codebook"
enableGitInfo = true

[menu]

[[menu.after]]
name = ""
weight = 1

[[menu.after]]
name = "Quick Links"
weight = 5

[[menu.after]]
name = "About STRONG AYA"
url = "https://strongaya.eu"
weight = 10

[[menu.after]]
name = "Github"
url = "https://github.com/STRONGAYA/AYA-cancer-data-schema"
weight = 20

[[menu.after]]
name = "Associated scientific publication (in preparation)"
url = ""
weight = 30

[params]
BookTheme = 'auto'
BookToC = false
BookFavicon = 'favicon.ico'
BookSection = 'AYA-cancer-data-schema'

# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = 'https://github.com/STRONGAYA/AYA-cancer-data-schema'