name: Deploy Hugo site to Pages

on:
  push:
    branches: [ "main", "dev/misc/hugo-codebook" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */3 *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: hugo

      - name: Generate Hugo content (capture warnings)
        id: generate
        run: |
          # Run the script and capture its logs
          node generate_hugo_content.js "${{ secrets.BIOPORTAL_API_KEY }}" 2>&1 | tee generate.log

          # Extract any warnings from the logs (lines containing "::warning").
          # Store them as a multi-line output for use in other jobs/steps.
          WARNINGS=$(grep "::warning" generate.log || true)

          # Save warnings as a multi-line step output
          echo "warnings<<EOF" >> $GITHUB_OUTPUT
          echo "$WARNINGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Also set a boolean flag if we found any warnings
          if [ -n "$WARNINGS" ]; then
            echo "warnings-found=true" >> $GITHUB_OUTPUT
          else
            echo "warnings-found=false" >> $GITHUB_OUTPUT
        working-directory: hugo

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
        working-directory: hugo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: hugo/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

create-issue-on-warning:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs['generate.warnings-found'] == 'true'
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const warnings = process.env['WARNINGS'] || 'No warnings captured.';
            
            // Nicely format the warnings inside a code block
            const bodyContent = `The following warnings were found during the Hugo content generation step:

                                 \`\`\`
                                 ${warnings}
                                 \`\`\`

                                  Please check the workflow logs for more details.
                                `;
            
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Attention: Missing Ontology Codes Detected",
              body: bodyContent
            });
        env:
          WARNINGS: ${{ needs.build.outputs['generate.warnings'] }}